version: '3.5'
services:
  mongo:
    image: mongo:latest
    container_name: mongoBD
    networks:
      - graylog
  elasticsearch:
    image: elasticsearch:6.8.18
    container_name: elastic
    networks:
      - graylog    
  graylog:  
    image: graylog/graylog:4.1.3
    container_name: graylog
    volumes:
      - ./config:/usr/share/graylog/data/config
    #restart: always
    links:
      - mongo
      - elasticsearch
    networks:
      - graylog
    ports:
      # Graylog web interface and REST API      
      - 9000:9000
      # Syslog TCP input
      - 514:514
      # Raw/Plaintext input
      - 5555:5555
    depends_on:
      - mongo
      - elasticsearch
networks:
  graylog:
